# Generated by Django 5.0.7 on 2024-07-12 18:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, help_text='Номер телефона, важно указать для интеграции с Telegram', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
