# Generated by Django 5.0.7 on 2024-07-12 19:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона, важно указать для интеграции с Telegram. Пример: +7 (900) 910 1000', max_length=128, region=None, unique=True),
        ),
    ]
