# Generated by Django 5.0.7 on 2024-07-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='ID пользователя в Telegram,                                            нужен для итеграции с Телеграмом и рассылки напоминаний', null=True, verbose_name='ID пользователя в телеграмме'),
        ),
    ]
