# Generated by Django 5.0.7 on 2024-07-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, help_text='ID чата в Telegram,                                            нужен для итеграции с Телеграмом и рассылки напоминаний', null=True, verbose_name='ID чата в телеграмме'),
        ),
    ]
