# Generated by Django 5.0.7 on 2024-07-30 18:05

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона,        важно указать для интеграции с Telegram.            Пример: +7 (900) 910 1000', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(blank=True, help_text='ID чата в Telegram,                                    нужен для итеграции с                                    Телеграмом и рассылки напоминаний', null=True, verbose_name='ID чата в телеграмме'),
        ),
    ]
