# Generated by Django 5.0.7 on 2024-07-13 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место обозначающее выполнение привычки', max_length=200, verbose_name='место выполнения привычки')),
                ('action', models.TextField(help_text='Выполняемое действие привычки', verbose_name='действие')),
                ('is_nice_habit', models.BooleanField(help_text='Поле обозначающее приятная ли эта привычка,                                            если привычка приятная она может быть только последней в цепочке', verbose_name='признак приятной привычки')),
                ('reward', models.TextField(blank=True, help_text='Вознаграждение за выполнение привычки', null=True, verbose_name='возраграждение')),
                ('time_to_done', models.DurationField(help_text='Неоходимое время для выполнения привычки, не должно быть более чем                                            120 сек. или 2 минуты,                                                Пример использования: 1:30, 2:00, 0:30', verbose_name='время выполнения')),
                ('is_published', models.BooleanField(default=False, help_text='Значение публичности, значение True дает возможность видеть эту привычку другим пользователям', verbose_name='публичность')),
                ('owner', models.ForeignKey(help_text='Создатель привычки', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
                ('periodic', models.ForeignKey(help_text='Установленная периодичность для выполнения,                                        устанавливается так же для отправки напоминаний.                                            Пример использования: 180/0/0 - 180 дней, 0/20/0 - 20 часов, 0/0/30 - 30 минут,                                                только одно из значений может быть указано, остальное "0"', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule', verbose_name='периодичность')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Связанная привычка, создает некую цепочку из привычек.                                          Последняя привычка может быть "Приятной",                                              в этом случае она может быть только последней', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='habits.habit', verbose_name='связанная привычка')),
                ('time_to_do', models.ForeignKey(help_text='Установленное время в которое будет выполнена привычка,                                       пример использования: 8:40, 00:30, 18:40', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='время выполнения привычки')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
