# Generated by Django 5.0.7 on 2024-07-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ('-time_to_do__hour',), 'verbose_name': 'Habit', 'verbose_name_plural': 'Habits'},
        ),
    ]
