# Generated by Django 5.0.7 on 2024-07-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Связанная привычка, создает некую цепочку из привычек.                                          Последняя привычка может быть "Приятной",                                              в этом случае она может быть только последней', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='habits.habit', verbose_name='связанная привычка'),
        ),
    ]
