# Generated by Django 5.0.7 on 2024-07-20 18:15

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': [django.db.models.functions.comparison.Cast('time_to_do__hour', output_field=models.IntegerField())], 'verbose_name': 'Habit', 'verbose_name_plural': 'Habits'},
        ),
    ]
