# Generated by Django 5.0.7 on 2024-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='url_bot',
            field=models.URLField(default='https://t.me/alex_pavlov_test_bot', help_text='адресс телеграмм бота для комуникации', verbose_name='адресс бота'),
        ),
    ]
