# Generated by Django 5.0.7 on 2024-07-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('habits', '0008_habit_url_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodic',
            field=models.ForeignKey(help_text='Установленная периодичность для выполнения,                                        устанавливается так же для отправки напоминаний.                                            Пример использования: 180/0/0 - 180 дней, 0/20/0 - 20 часов, 0/0/30 - 30 минут,                                                только одно из значений может быть указано, остальное "0"', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_do',
            field=models.ForeignKey(help_text='Установленное время в которое будет выполнена привычка,                                       пример использования: 8:40, 00:30, 18:40', on_delete=django.db.models.deletion.CASCADE, related_name='cron', to='django_celery_beat.crontabschedule', verbose_name='время выполнения привычки'),
        ),
    ]
