# Generated by Django 5.0.7 on 2024-07-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('habits', '0009_alter_habit_periodic_alter_habit_time_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_nice_habit',
            field=models.BooleanField(help_text='Поле обозначающее приятная ли эта привычка, если привычка приятная она может быть только последней в цепочке', verbose_name='признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodic',
            field=models.ForeignKey(help_text='Установленная периодичность для выполнения, устанавливается так же для отправки напоминаний. Пример использования: 180/0/0 - 180 дней, 0/20/0 - 20 часов,0/0/30 - 30 минут,только одно из значений может быть указано, остальное "0"', on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule', verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Связанная привычка, создает некую цепочку из привычек. Последняя привычка может быть "Приятной", в этом случае она может быть только последней', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related', to='habits.habit', verbose_name='связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_do',
            field=models.ForeignKey(help_text='Установленное время в которое будет выполнена привычка, пример использования: 8:40, 00:30, 18:40', on_delete=django.db.models.deletion.CASCADE, related_name='cron', to='django_celery_beat.crontabschedule', verbose_name='время выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_done',
            field=models.DurationField(help_text='Неоходимое время для выполнения привычки, не должно быть более чем 120 сек. или 2 минуты, Пример использования: 1:30, 2:00, 0:30', verbose_name='время выполнения'),
        ),
    ]
